### ISSUE TITLE
FOR / icecoder: https is required for this addon to work properly

### ISSUE THREAD

**Issue by Koala** [Koala/ListeZumAbarbeitenWennZeitIst#5]
https://github.com/FriendsOfREDAXO/icecoder/issues/24

Mal abarbeiten bei nächster Gelegenheit.
Evtl. könnte da auch irgendwo eine Prüfung auf ssl/https rein? Zumindest die Beschreibung könnte angepasst werden.

**Comment by skerbis** [comment]
Ich denke das wird nicht nötig sein. Da die Weiterentwicklung des IceCoder-Vendors unsicher ist.

**Comment by Koala** [comment]
Wird geschlossen wegen:

![image](https://github.com/Koala/ListeZumAbarbeitenWennZeitIst/assets/330686/f684848e-6e48-4f49-884a-7d4c06786fc2)
